const initialState = {
  topcloth: [
    {
      id: 'topcloth_1',
      type: 'topclothes',
      name: '上衣1',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/topcloth1.png',
      imgSrc_png: './images/clothes/topcloth1.png',
    },
    {
      id: 'topcloth_2',
      type: 'topclothes',
      name: '上衣2',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/topcloth2.png',
      imgSrc_png: './images/clothes/topcloth2.png',
    },
    {
      id: 'topcloth_3',
      type: 'topclothes',
      name: '上衣3',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/topcloth3.png',
      imgSrc_png: './images/clothes/topcloth3.png',
    },
    {
      id: 'topcloth_4',
      type: 'topclothes',
      name: '上衣4',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/topcloth4.png',
      imgSrc_png: './images/clothes/topcloth4.png',
    },
    {
      id: 'topcloth_5',
      type: 'topclothes',
      name: '上衣5',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/topcloth5.png',
      imgSrc_png: './images/clothes/topcloth5.png',
    },
    {
      id: 'topcloth_6',
      type: 'topclothes',
      name: '上衣6 ',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/topcloth6.png',
      imgSrc_png: './images/clothes/topcloth6.png',
    },
  ],
  botcloth: [
    {
      id: 'botcloth_1',
      type: 'botclothes',
      name: '下身1',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/botcloth1.png',
      imgSrc_png: './images/clothes/botcloth1.png',
    },
    {
      id: 'botcloth_2',
      type: 'botclothes',
      name: '下身2',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/botcloth2.png',
      imgSrc_png: './images/clothes/botcloth2.png',
    },
    {
      id: 'botcloth_3',
      type: 'botclothes',
      name: '下身3',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/botcloth3.png',
      imgSrc_png: './images/clothes/botcloth3.png',
    },
    {
      id: 'botcloth_4',
      type: 'botclothes',
      name: '下身4',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/botcloth4.png',
      imgSrc_png: './images/clothes/botcloth4.png',
    },
    {
      id: 'botcloth_5',
      type: 'botclothes',
      name: '下身5',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/clothes/botcloth5.png',
      imgSrc_png: './images/clothes/botcloth5.png',
    },
  ],
  shoes: [
    {
      id: 'shoes_1',
      type: 'shoes',
      name: '鞋子1',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/shoes/shoes1.png',
      imgSrc_png: './images/shoes/shoes1.png',
    },
    {
      id: 'shoes_2',
      type: 'shoes',
      name: '鞋子2',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/shoes/shoes2.png',
      imgSrc_png: './images/shoes/shoes2.png',
    },
    {
      id: 'shoes_3',
      type: 'shoes',
      name: '鞋子3',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/shoes/shoes3.png',
      imgSrc_png: './images/shoes/shoes3.png',
    },
    {
      id: 'shoes_4',
      type: 'shoes',
      name: '鞋子4',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/shoes/shoes4.png',
      imgSrc_png: './images/shoes/shoes4.png',
    },
    {
      id: 'shoes_5',
      type: 'shoes',
      name: '鞋子5',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/shoes/shoes5.png',
      imgSrc_png: './images/shoes/shoes5.png',
    },
  ],
  handbags: [
    {
      id: 'handbag_1',
      type: 'handbags',
      name: '包包1',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/handbags/handbag1.png',
      imgSrc_png: './images/handbags/handbag1.png',
    },
    {
      id: 'handbag_2',
      type: 'handbags',
      name: '包包2',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/handbags/handbag2.png',
      imgSrc_png: './images/handbags/handbag2.png',
    },
    {
      id: 'handbag_3',
      type: 'handbags',
      name: '包包3',
      desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid, nulla.',
      imgSrc_jpg: './images/handbags/handbag3.png',
      imgSrc_png: './images/handbags/handbag3.png',
    },
  ],
};

const ProductListReducer = (state = initialState, action) => {
  return { ...state };
};

export default ProductListReducer;
